PFAS_DB = {
    'PFOA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟辛酸',
        'name_en': 'Perfluorooctanoic Acid',
        'cas': '335-67-1',
        'category': '全氟羧酸（PFCA）',
        'chain': 8,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C8HF15O2',
        'mol_weight': 414.07
    },
    'PFOS': {
        'smiles': 'OS(=O)(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟辛烷磺酸',
        'name_en': 'Perfluorooctane Sulfonic Acid',
        'cas': '1763-23-1',
        'category': '全氟磺酸（PFSA）',
        'chain': 8,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C8HF17O3S',
        'mol_weight': 500.13
    },
    'GenX': {
        'smiles': 'OC(=O)C(F)(F)OC(F)(F)C(F)(F)OC(F)(F)F',
        'name_cn': '六氟环氧丙烷二聚体酸',
        'name_en': 'Hexafluoropropylene Oxide Dimer Acid (HFPO-DA)',
        'cas': '13252-13-6',
        'category': '全氟醚羧酸（PFECDA）',
        'chain': 3,
        'toxicity': '中',
        'degrade': '较难降解',
        'bioaccum': '中',
        'mol_formula': 'C5HF9O4',
        'mol_weight': 296.04
    },
    'PFNA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟壬酸',
        'name_en': 'Perfluorononanoic Acid',
        'cas': '375-95-1',
        'category': '全氟羧酸（PFCA）',
        'chain': 9,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C9HF17O2',
        'mol_weight': 464.08
    },
    'PFDA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟癸酸',
        'name_en': 'Perfluorodecanoic Acid',
        'cas': '335-76-2',
        'category': '全氟羧酸（PFCA）',
        'chain': 10,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '极高',
        'mol_formula': 'C10HF19O2',
        'mol_weight': 514.08
    },
    'PFHxA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟己酸',
        'name_en': 'Perfluorohexanoic Acid',
        'cas': '307-24-4',
        'category': '全氟羧酸（PFCA）',
        'chain': 6,
        'toxicity': '中',
        'degrade': '较难降解',
        'bioaccum': '中',
        'mol_formula': 'C6HF11O2',
        'mol_weight': 314.05
    },
    'PFBS': {
        'smiles': 'OS(=O)(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟丁烷磺酸',
        'name_en': 'Perfluorobutane Sulfonic Acid',
        'cas': '375-73-5',
        'category': '全氟磺酸（PFSA）',
        'chain': 4,
        'toxicity': '中',
        'degrade': '较难降解',
        'bioaccum': '低',
        'mol_formula': 'C4HF9O3S',
        'mol_weight': 300.10
    },
    'PFHxS': {
        'smiles': 'OS(=O)(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟己烷磺酸',
        'name_en': 'Perfluorohexane Sulfonic Acid',
        'cas': '355-46-4',
        'category': '全氟磺酸（PFSA）',
        'chain': 6,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C6HF13O3S',
        'mol_weight': 400.12
    },
    'PFBA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟丁酸',
        'name_en': 'Perfluorobutanoic Acid',
        'cas': '375-22-4',
        'category': '全氟羧酸（PFCA）',
        'chain': 4,
        'toxicity': '低',
        'degrade': '可降解',
        'bioaccum': '低',
        'mol_formula': 'C4HF7O2',
        'mol_weight': 214.04
    },
    'PFPeA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟戊酸',
        'name_en': 'Perfluoropentanoic Acid',
        'cas': '2706-90-3',
        'category': '全氟羧酸（PFCA）',
        'chain': 5,
        'toxicity': '中',
        'degrade': '较难降解',
        'bioaccum': '低',
        'mol_formula': 'C5HF9O2',
        'mol_weight': 264.04
    },
    'PFUnDA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟十一烷酸',
        'name_en': 'Perfluoroundecanoic Acid',
        'cas': '2058-94-8',
        'category': '全氟羧酸（PFCA）',
        'chain': 11,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '极高',
        'mol_formula': 'C11HF21O2',
        'mol_weight': 564.09
    },
    'FOSA': {
        'smiles': 'NC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟辛烷磺酰胺',
        'name_en': 'Perfluorooctane Sulfonamide',
        'cas': '754-91-6',
        'category': '全氟磺酰胺（FASA）',
        'chain': 8,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C8H2F17NO2S',
        'mol_weight': 499.14
    },
    'ADONA': {
        'smiles': 'OC(=O)C(F)(F)OC(F)(F)C(F)(F)OC(F)(F)C(F)(F)OC(F)(F)C(F)(F)F',
        'name_cn': '4,8-二氧杂-3H-全氟壬酸',
        'name_en': '4,8-Dioxa-3H-perfluorononanoic Acid',
        'cas': '919005-14-4',
        'category': '全氟醚羧酸（PFECDA）',
        'chain': 4,
        'toxicity': '中',
        'degrade': '较难降解',
        'bioaccum': '中',
        'mol_formula': 'C8HF15O5',
        'mol_weight': 462.06
    },
    'TFA': {
        'smiles': 'OC(=O)C(F)(F)F',
        'name_cn': '三氟乙酸',
        'name_en': 'Trifluoroacetic Acid',
        'cas': '76-05-1',
        'category': '全氟羧酸（PFCA）',
        'chain': 2,
        'toxicity': '低',
        'degrade': '可降解',
        'bioaccum': '低',
        'mol_formula': 'C2HF3O2',
        'mol_weight': 114.02
    },
    'TFMS': {
        'smiles': 'OS(=O)(=O)C(F)(F)F',
        'name_cn': '三氟甲磺酸',
        'name_en': 'Trifluoromethanesulfonic Acid',
        'cas': '1493-13-6',
        'category': '全氟磺酸（PFSA）',
        'chain': 1,
        'toxicity': '低',
        'degrade': '可降解',
        'bioaccum': '低',
        'mol_formula': 'CHF3O3S',
        'mol_weight': 150.08
    },
    '6:2 FTCA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)CC',
        'name_cn': '6:2氟调聚物羧酸',
        'name_en': '6:2 Fluorotelomer Carboxylic Acid',
        'cas': '27854-31-5',
        'category': '氟调聚物羧酸（FTCA）',
        'chain': 8,
        'toxicity': '中',
        'degrade': '较难降解',
        'bioaccum': '中',
        'mol_formula': 'C8HF14O2',
        'mol_weight': 392.06
    },
    '8:2 FTCA': {
        'smiles': 'OC(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)CC',
        'name_cn': '8:2氟调聚物羧酸',
        'name_en': '8:2 Fluorotelomer Carboxylic Acid',
        'cas': '27854-30-4',
        'category': '氟调聚物羧酸（FTCA）',
        'chain': 10,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C10HF18O2',
        'mol_weight': 492.07
    },
    '9Cl-PF3ONS': {
        'smiles': 'OS(=O)(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(Cl)F',
        'name_cn': '9-氯代全氟壬烷磺酸',
        'name_en': '9-Chlorohexadecafluoro-3-nonanesulfonic Acid',
        'cas': '756426-58-1',
        'category': '氯代多氟醚磺酸（Cl-PFAES）',
        'chain': 9,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C9HClF18O3S',
        'mol_weight': 566.59
    },
    'N-EtFOSE': {
        'smiles': 'CCN(CCO)S(=O)(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': 'N-乙基全氟辛烷磺酰胺乙醇',
        'name_en': 'N-Ethyl Perfluorooctane Sulfonamidoethanol',
        'cas': '1691-99-2',
        'category': '全氟磺酰胺乙醇（FASE）',
        'chain': 8,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '高',
        'mol_formula': 'C12H10F17NO4S',
        'mol_weight': 571.24
    },
    'PFDS': {
        'smiles': 'OS(=O)(=O)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
        'name_cn': '全氟癸烷磺酸',
        'name_en': 'Perfluorodecane Sulfonic Acid',
        'cas': '335-77-3',
        'category': '全氟磺酸（PFSA）',
        'chain': 10,
        'toxicity': '高',
        'degrade': '难降解',
        'bioaccum': '极高',
        'mol_formula': 'C10HF21O3S',
        'mol_weight': 600.14
    },
}